import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import AuthProvider from "../components/authProvider/AuthProvider";
import QueryProvider from "../components/queryClientProvider/queryClient";
import { Theme } from "@radix-ui/themes";
import Header from "../components/header/Header";
import SearchBar from "../components/searchBar/SearchBar";
import ProductTypes from "../components/productTypes/ProductTypes";
import Footer from "../components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <QueryProvider>
            <Theme>
              <div className="flex justify-center items-center w-full ">
                <div className="w-3/4 flex justify-between items-center flex-col h-screen">
                  <div className="w-full">
                    <Header />
                    <SearchBar />
                    <ProductTypes />
                  </div>
                  <div className="w-full">{children}</div>
                  <div className="w-full">
                    <Footer />
                  </div>
                </div>
              </div>
            </Theme>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
